version: "3"
networks:
  delne:
    name: delne
services:
  delne:
    image: haidousm/delne:development-amd64
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./delne.db:/src/app/delne.db
      - ./delne.toml:/src/app/delne.toml
      - /src/app/letsencrypt:/src/app/letsencrypt
    restart: always
    pull_policy: always
    networks:
      - delne
